#!/usr/bin/expect -f

set PASSWORDSSH "password"

set timeout 5

spawn rsync -av -e "ssh -l user" /path/to/tmp/oc-data/[lindex $argv 0] user@example.com:~/path/to/base/[lindex $argv 0]

expect "password:" { send "$PASSWORDSSH\n"}
